baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://localhost:4000/resumecards/" # the base hostname & protocol for your site

site:
    data:
        resume:
            demo: false

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
